name: CI for testing form_response app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        redis-version: [4]
        mongodb-version: [3.6,4.0]

    steps:
    - uses: actions/checkout@v2
    # setup node
    - name: set node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        always-auth: true
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope:  "@teamyourcircle"
    - run: npm ci
    - run: npm i mocha --save-dev
    - run: npm run build --if-present
    - run: npm test    
    # set up rabbitmq
    - name: set rabbitmq
      uses: nijel/rabbitmq-action@v1.0.0
      with:
        rabbitmq version: '3.8'    
    #setup mongo
    - name: set mongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    #setup redis        
    - name: set redis v${{ matrix.redis-version }}
      uses: superchargejs/redis-github-action@1.1.0
      with:
        redis-version: ${{ matrix.redis-version }}

